### PR TITLE
Support hostPath in VolumeSource.

### PR DESCRIPTION
**Pull request by skolosov-snap**
Support hostPath volume type in VolumeSource.

### CODE REVIEW

**Comment by ashishshinde** [comment]
@skolosov-snap Do you have a use case for using hostPath with Aerospike? Or is this driven by some sidecar or init-container needing access to hostPath? We had left this out because of the inherent security risk and lack of a valid use case.

**Comment by skolosov-snap** [comment]
> @skolosov-snap Do you have a use case for using hostPath with Aerospike? Or is this driven by some sidecar or init-container needing access to hostPath? We had left this out because of the inherent security risk and lack of a valid use case.

Yes. We got rid of using EBS for storing SMD because EBS nvme devices messed up with with local SSD after rebooting. Thus we start getting an issue with using EBS. We tried to fix it by linking PVs (in Local Volume Provisioner) to devices using links based on device serial umbers. But for some reason it didn't work. And event for correctly created links Pods still sees naming which was before node restarts. We are discussing it with AWS guy right now.
In addition to that it seems us correct to tire SDM to data on the same node (local ssd). If Pod will be rescheduled to another node SDM will be migrated to that node, but data will not be.

**Comment by unix-way** [comment]
I've also been working on this. Your PR does not cover the use case of mounting hostPaths as block devices. Mine does https://github.com/aerospike/aerospike-kubernetes-operator/pull/137

**Comment by skolosov-snap** [comment]
> I've also been working on this. Your PR does not cover the use case of mounting hostPaths as block devices. Mine does #137

Thanks, Kirill. Yes, we haven't supported DeviceBlock mode for hostPath. I'm happy to use your PR instead.

**Comment by sud82** [comment]
Duplicate of #137

**Pull request closed without merging**
